const a= 0;
try{
    const b= 0;
}
catch{
    console.log(1);
}
console.log(b);